name: Update Version inside PHP Code

on:
  push:
    tags:
      - 'v*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Inject new version tag into Controller.php
      run: |
        # Берем имя тега из события push (например, refs/tags/v2.1.2) и чистим до 2.1.2
        VERSION_NUM=$(echo "${{ github.ref_name }}" | sed 's/^v//')
        sed -i -E "s/(const VERSION\s*=\s*['\"])[^'\"]*['\"]/\1$VERSION_NUM'/g" core/Controller.php

    - name: Commit and Push automatically updated version
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: auto-update framework version to ${{ github.ref_name }} [skip ci]"
        file_pattern: 'core/Controller.php'
        branch: main
